apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - blackbox-exporter.yaml
  - backend-servicemonitor.yaml
  - backend-prometheusrule.yaml
  - grafana-dashboard-backend.yaml
