apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: remnawave
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

